# Generated by Django 4.2 on 2023-04-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time',
            new_name='time_to_complete',
        ),
    ]
