# Generated by Django 4.2 on 2023-04-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0002_rename_time_task_time_to_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('URGENT', 'urgent'), ('DO', 'do'), ('DEFER', 'defer')], default='DO'),
        ),
    ]
