# Generated by Django 4.2 on 2023-04-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0006_alter_task_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_status',
            field=models.CharField(choices=[('CP', 'completed'), ('IC', 'incomplete')], default='IC', max_length=2),
        ),
    ]
