# Generated by Django 4.2 on 2023-04-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0007_task_completed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_status',
            field=models.CharField(choices=[('COMPLETED', 'completed'), ('INCOMPLETE', 'incomplete')], default='INCOMPLETE'),
        ),
    ]
